//
//  CVViewerRouter.swift
//  Simple-Resume
//
//  Created by Mar Koss on 2020-04-04.
//  Copyright (c) 2020 Mar Koss. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CVViewerRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CVViewerDataPassing
{
  var dataStore: CVViewerDataStore? { get }
}

class CVViewerRouter: NSObject, CVViewerRoutingLogic, CVViewerDataPassing
{
  weak var viewController: CVViewerViewController?
  var dataStore: CVViewerDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CVViewerViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CVViewerDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
