//
//  CVViewerModels.swift
//  Simple-Resume
//
//  Created by Mar Koss on 2020-04-04.
//  Copyright (c) 2020 Mar Koss. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CVViewer
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
