//
//  CVViewerInteractor.swift
//  Simple-Resume
//
//  Created by Mar Koss on 2020-04-04.
//  Copyright (c) 2020 Mar Koss. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CVViewerBusinessLogic
{
  func doSomething(request: CVViewer.Something.Request)
}

protocol CVViewerDataStore
{
  //var name: String { get set }
}

class CVViewerInteractor: CVViewerBusinessLogic, CVViewerDataStore
{
  var presenter: CVViewerPresentationLogic?
  var worker: CVViewerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CVViewer.Something.Request)
  {
    worker = CVViewerWorker()
    worker?.doSomeWork()
    
    let response = CVViewer.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
